name: MainCI
on:
  workflow_run:
    workflows:
      - "Run Tests"
    types:
      - completed
    branches:
      - "main"
jobs:
  on-success:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v1
      - name: Run a one-line script
      - run: echo 'The triggering workflow passed'
  on-failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
